### PR TITLE
Added TIC Token to Defaults

### PR DESCRIPTION
**Pull request by trustinvest**

### CODE REVIEW

**Comment by gamalielhere** [comment]
@trustinvest please change the file name to `<token address>.json`

**Comment by trustinvest** [comment]
I have a question, Is my coin listed myetherwallet?

**Comment by trustinvest** [comment]
@gamalielhere
I have a question, Is my coin listed on myetherwallet?

**Comment by gamalielhere** [comment]
@trustinvest it will be once we merge it over to myetherwallet.

**Pull request merged**
