### PR TITLE
Update urls-darklist.json

### PR DESCRIPTION
**Pull request by sekisanchi**
omg-omise.com
Phish: fake bounty campaign implying connected with OMG, redirect into https://myethierwallet.com/wallet-info.php

myetherwallet__open-source___client-side_ether_wallet

### CODE REVIEW

**Comment by sekisanchi** [comment]
slack_-_matchpool
fullscreen_2017_10_01_8_30

**Comment by sekisanchi** [comment]
myetherwalletiy.com

slack_-_chronobank_io

myetherwallet

**Comment by sekisanchi** [comment]
myetherwalletiu.com

slack_-_matchpool

myetherwallet

**Comment by sekisanchi** [comment]
myetherwalletiq.com

slack_-_matchpool

myetherwallet

**Comment by sekisanchi** [comment]
Tried to adding dup, and restored.

**Comment by 409H** [comment]
Good work - thank you!

**Pull request merged**
