### PR TITLE
Update JOB Token in MEW List

### PR DESCRIPTION
**Pull request by JobchainOfficial**
Dear MEW Team, 

we have proceeded with an update of our smart contract. 

Please update to the new JOB smart contract. Thank you.

### CODE REVIEW

**Comment by gamalielhere** [comment]
@JobchainOfficial is there any announcement for this? A blog post of sorts?

**Comment by JobchainOfficial** [comment]
Yes, please check blog.jobchain.com. You can see the announcement in the latest post. Also, in our telegram channel t.me/JobchainAnnouncements.

The swap has been completed already in etherscan.


Jobchain Team
Jobchain e.U. | DC Tower, Donau-City-Strasse 7, 1220 Vienna, Austria |
E-mail: info@jobchain.com<mailto:info@jobchain.com> | T: (+43) 660 132 75 87

[Jobchain152-2-Logo-1-Blue-1-pt-TM-Big]<https://www.jobchain.com>
Follow us on www.jobchain.com<http://www.jobchain.com/>
[Discord]<https://discord.gg/jb6rFgE>[facebook]<https://www.facebook.com/jobchainofficial/>[Instagram]<https://www.instagram.com/jobchain/>[Telegram]<https://t.me/JobchainOfficial>[twitter]<https://twitter.com/Jobchain>[reddit]<https://www.reddit.com/u/JobchainTechnologies>

This email message is intended only for the use of the named recipient. Information contained in this email message and its attachments may be privileged, confidential and protected from disclosure. If you are not the intended recipient, please do not read, copy, use or disclose this communication to others. Also please notify the sender by replying to this message and then delete it from your system.

________________________________
De: gamalielhere <notifications@github.com>
Enviado: Monday, January 27, 2020 8:48:51 PM
Para: MyEtherWallet/ethereum-lists <ethereum-lists@noreply.github.com>
Cc: Jobchain Team <info@jobchain.com>; Mention <mention@noreply.github.com>
Asunto: Re: [MyEtherWallet/ethereum-lists] Update JOB Token in MEW List (#1406)


@JobchainOfficial<https://github.com/JobchainOfficial> is there any announcement for this? A blog post of sorts?

**Comment by JobchainOfficial** [comment]
Thank you,

The Jobchain Team
[Jobchain152 2 Logo 4 Blue (4 pt)]
Follow us on www.jobchain.com<https://nam01.safelinks.protection.outlook.com/?url=www.jobchain.com&data=02%7C01%7C%7C39f407af697e4695fe7408d6bcf173d3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636904142549580106&sdata=xOOsSFn7FJnuy%2FKOXIPGgzZUYDYd49o8OPfv9f0OI5I%3D&reserved=0>
[signature_792190196]<http://https/twitter.com/jobchain>[signature_2038852561]<https://facebook.com/jobchainofficial>[signature_326757890]<https://instagram.com/jobchain>[Imagen que contiene imágenes prediseñadas  Descripción generada automáticamente]<https://linkedin.com/company/jobchainofficial>[signature_1309765752]<https://www.medium.com/jobchain>[signature_525930960]<https://t.me/JobchainOfficial>

Copyright © 2020 Jobchain®, All Rights Reserved.

This email message is intended only for the use of the named recipient. Information contained in this email message and its attachments may be privileged, confidential and protected from disclosure. If you are not the intended recipient, please do not read, copy, use or disclose this communication to others. Also please notify the sender by replying to this message and then delete it from your system.



De: gamalielhere <notifications@github.com>
Responder a: MyEtherWallet/ethereum-lists <reply@reply.github.com>
Fecha: miércoles, 29 de enero de 2020, 17:41
Para: MyEtherWallet/ethereum-lists <ethereum-lists@noreply.github.com>
CC: Jobchain Team <info@jobchain.com>, Mention <mention@noreply.github.com>
Asunto: Re: [MyEtherWallet/ethereum-lists] Update JOB Token in MEW List (#1406)


@gamalielhere approved this pull request.

**Comment by JobchainOfficial** [comment]
Dear @gamalielhere, 

It seems that in MEW it´s still the old JOB instead of the new one (0xdfbc9050F5B01DF53512DCC39B4f2B2BBaCD517A). Can you please double check please?

Thank you, 
Captura de pantalla 2020-01-31 a las 12 01 12

**Comment by gamalielhere** [comment]
@JobchainOfficial can you double check again?

**Comment by JobchainOfficial** [comment]
Thank you.

It´s working now.

Sincerely,

The Jobchain Team
[Jobchain152 2 Logo 4 Blue (4 pt)]
Follow us on www.jobchain.com<https://nam01.safelinks.protection.outlook.com/?url=www.jobchain.com&data=02%7C01%7C%7C39f407af697e4695fe7408d6bcf173d3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636904142549580106&sdata=xOOsSFn7FJnuy%2FKOXIPGgzZUYDYd49o8OPfv9f0OI5I%3D&reserved=0>
[signature_1123605445]<http://https/twitter.com/jobchain>[signature_916194325]<https://facebook.com/jobchainofficial>[signature_753499779]<https://instagram.com/jobchain>[Imagen que contiene imágenes prediseñadas  Descripción generada automáticamente]<https://linkedin.com/company/jobchainofficial>[signature_699797582]<https://www.medium.com/jobchain>[signature_2027422370]<https://t.me/JobchainOfficial>

Copyright © 2020 Jobchain®, All Rights Reserved.

This email message is intended only for the use of the named recipient. Information contained in this email message and its attachments may be privileged, confidential and protected from disclosure. If you are not the intended recipient, please do not read, copy, use or disclose this communication to others. Also please notify the sender by replying to this message and then delete it from your system.



De: gamalielhere <notifications@github.com>
Responder a: MyEtherWallet/ethereum-lists <reply@reply.github.com>
Fecha: viernes, 31 de enero de 2020, 20:13
Para: MyEtherWallet/ethereum-lists <ethereum-lists@noreply.github.com>
CC: Jobchain Team <info@jobchain.com>, Mention <mention@noreply.github.com>
Asunto: Re: [MyEtherWallet/ethereum-lists] Update JOB Token in MEW List (#1406)


@JobchainOfficial<https://github.com/JobchainOfficial> can you double check again?

**Pull request merged**
