### PR TITLE
Update OHNI Token

### PR DESCRIPTION
**Pull request by jamesohni**
URGENT

### CODE REVIEW

**Comment by gamalielhere** [comment]
@jamesohni do you have any documentation or announcement of some sort for the change?

**Comment by jamesohni** [comment]
It is available at ohni.us/press.pdf and also in our telegram t.me/OhniGroup

We already made the change and would like the contract abi added asap. It was there and I noticed that it was removed.

Thanks!

James
Ohni CEO

(My new email is james@ohni.us)

---- On Mon, 12 Mar 2018 12:51:50 -0700 notifications@github.com wrote ----

@jamesohni do you have any documentation or announcement of some sort for the change?

**Comment by gamalielhere** [comment]
@jamesohni sounds good. I'll try and get this merged in today.

**Comment by jamesohni** [comment]
Ok thanks. The sooner the better :)

**Comment by jamesohni** [comment]
Could you also do the ABI?

That is the most important. I made a pull request for that.

---- On Mon, 12 Mar 2018 13:07:25 -0700 notifications@github.com wrote ----

@jamesohni sounds good. I'll try and get this merged in today.

**Comment by gamalielhere** [comment]
@jamesohni yes. I'll look over that in a moment.

**Comment by jamesohni** [comment]
Great thanks. It threw an error for some reason. Please let me if I need to fix something.

---- On Mon, 12 Mar 2018 13:11:43 -0700 notifications@github.com wrote ----

@jamesohni yes. I'll look over that in a moment.

**Pull request merged**
