### PR TITLE
0x5aaa2182459377b6ca18b10712f9f602140764af.json

### PR DESCRIPTION
**Pull request by elevationp**
The Elevation Platform is a great project

### CODE REVIEW

**Comment by gamalielhere** [comment]
Is there any reason why you're replacing another token?

**Comment by elevationp** [comment]
> 
> 
> Is there any reason why you're replacing another token?

I needed to create a profile for my token on imtoken

**Comment by gamalielhere** [comment]
@elevationp you don't have to delete another token to create a new file.

**Comment by elevationp** [comment]
ok

**Pull request closed without merging**
