### PR TITLE
Update UMKA token address

### PR DESCRIPTION
**Pull request by rumsterrt**

### CODE REVIEW

**Comment by gamalielhere** [comment]
@rumsterrt is there any documentation about this change or an announcement of some sort?

**Comment by rumsterrt** [comment]
@gamalielhere, yes. You can see new address in umka.city. Go in "JOIN US" after click "JOIN US" under "Become an Investor". After that put any ethereum address into "Ethereum address for token reception" and click "Get address". Your can see new umka address into "UMKA Ethereum wallet address (send to ETH address)". Sorry it took so long. Thanks.

**Comment by rumsterrt** [comment]
@gamalielhere, of course. Just go in umka.city and click "BECOME AN INVESTOR". See this field "UMKA Ethereum wallet address (send to ETH address)". Sorry for taking so long.

**Comment by gamalielhere** [comment]
@rumsterrt awesome. Thanks!

**Pull request merged**
