### PR TITLE
Create 0x8Fb1a59cA2d57B51e5971A85277EFe72c4492983.json

### PR DESCRIPTION
**Pull request by daftoken**
logo
generate new tokens

### CODE REVIEW

**Review by farmingharry — APPROVED** [review]
Got the correct location

**Comment by daftoken** [comment]
@gamalielhere

**Review by gamalielhere — CHANGES_REQUESTED** [review]
please remove extra properties. Look at other submitted tokens or the README.md for more information

**Comment by daftoken** [comment]
{
"symbol": "DAF",
"name": "Diamonds are Forever",
"type": "BEP20",
"address": "0x8Fb1a59cA2d57B51e5971A85277EFe72c4492983",
"ens_address": "",
"decimals": 6,
"website": "http://daftoken.io",
"slippage": 5,
"Status": "active",
"description": "DAF is a DEFI token made for easy investors with the help from crypto experts.",
    "explorer": "https://bscscan.com/token/0x8fb1a59ca2d57b51e5971a85277efe72c4492983",
"logo": {
"src": "https://i.ibb.co/r65VgsJ/FFCD7-C1-D-FBEA-4413-8-B11-89-A4-A8981809.png",
"width": "32px",
"height": "32px",
"ipfs_hash": ""
},
"support": {
"email": "info@daftoken.io",
"url": "https://daftoken.io"
},
"social": {
"chat": "https://t.me/daftoken",
"discord": "https://discord.gg/DAFtoken#9454",
"facebook": "https://www.facebook.com/daftoken",
"github": "https://github.com/Frozenjeff/DAF",
"telegram": "https://t.me/daftoken",
"twitter": "https://twitter.com/daf_token",
  "id": "0x8fb1a59ca2d57b51e5971a85277efe72c4492983",
    "vested": [],
    "audits": []

}
}

**Pull request closed without merging**
