### PR TITLE
Report fake 'Atonomis' presale

### PR DESCRIPTION
**Pull request by petri**

### CODE REVIEW

**Comment by gamalielhere** [comment]
@petri is there any documentation/blog post or anything that says its a fake presale or is there a published dock for the actual Atonomis presale?

**Comment by petri** [comment]
@gamalielhere the fake site was pretending to be Atonomi (no trailing 's' letter). The scam was discovered by our staff and also Tweeted about by Atonomi: https://twitter.com/atonomi/status/989890078322450433 Also, we reported the site to Google and others & it seems the fake site is now down.

**Comment by petri** [comment]
@gamalielhere also, what do you mean by a published 'dock' ? Something to do with dock.io ?

**Comment by gamalielhere** [comment]
@petri *doc. I misspelled that. Thanks. I'll get this merged. it should show on our live site on our next release.

**Pull request merged**
