### PR TITLE
Create 0x03e8f56ad0D759BCFfF960863388Bfdb2efD.json1579

### PR DESCRIPTION
**Pull request by YearnfinanceCash**

### CODE REVIEW

**Review by gamalielhere — CHANGES_REQUESTED** [review]
Please follow the guideline found [here](https://github.com/MyEtherWallet/ethereum-lists#tokens)

**Comment by YearnfinanceCash** [comment]
> Пожалуйста, следуйте инструкциям, приведенным [здесь](https://github.com/MyEtherWallet/ethereum-lists#tokens)

Hello! What exactly and how do we need to do it?

**Comment by gamalielhere** [comment]
@YearnfinanceCash move it to the right folder or at least translate it to be in the right folder. `жетоны` should be `tokens`

**Review by YearnfinanceCash — COMMENTED** [review]
src/tokens/eth/0x03e8f56ad0D759BCFfF960863388Bfdb2efD.json1579

**Comment by kostya1001** [comment]
> src / tokens / eth / 0x03e8f56ad0D759BCFfF960863388Bfdb2efD.json1579

**Pull request closed without merging**
