### PR TITLE
(Reverted) Update and rename back to 0xA4Bdb11dc0a2bEC88d24A3aa1E6Bb17201112eBe.json

### PR DESCRIPTION
**Pull request by ftinetwork**

### CODE REVIEW

**Comment by ftinetwork** [comment]
> Please don't delete other tokens.

Opps, apologies for the inconvenience. 
Is there anything else I need to do at this point?

**Comment by gamalielhere** [comment]
@ftinetwork yes. revert the deleted file from your commit so the PR can be merged.

**Comment by ftinetwork** [comment]
@gamalielhere, OK hope I did what I was supposed to. PLMK if anything else. Thanks.

**Comment by gamalielhere** [comment]
closing as duplicate of #1191

**Pull request closed without merging**
