### PR TITLE
KPR Coin

### PR DESCRIPTION
**Pull request by Matt-KPR**
All info supplied to get registered
We are currently verified on Etherscan
https://etherscan.io/address/0xb5c33f965c8899d255c34cdd2a3efa8abcbb3dea

### CODE REVIEW

**Comment by SteveMieskoski** [comment]
@Matt-KPR could you add the token to the list in the existing file rather than a new file.  Thanks!

**Comment by Matt-KPR** [comment]
Hi thank you for the information, I'm not sure how to do that. I have read the link you sent and it is still not clear. Please explain what to do. Thank you

**Comment by SteveMieskoski** [comment]
@Matt-KPR I went ahead and added your token to the list used for the default tokens (tokens-eth.json), and reverted the prior changes.  I believe this is what was intended, but if I am wrong let me know and we can get it all straightened out.

**Comment by Matt-KPR** [comment]
Yes that's great, thank you very much. Sorry for being such a noob... 
You rock

Thanks again
Matt

**Pull request merged**
