### PR TITLE
Adds token for BitcoinAsia (BTCA)

### PR DESCRIPTION
**Pull request by bitcoinasiasite**
Added BitcoinAsia (BTCA) , World's first cryptocurrency based travel package company

### CODE REVIEW

**Comment by bitcoinasiasite** [comment]
Any update? How much time it will take to approve?

**Review by mj559940 — APPROVED** [review]

**Comment by mj559940** [comment]
> Added BitcoinAsia (BTCA) , World's first cryptocurrency based travel package company

**Review by mj559940 — APPROVED** [review]

**Comment by mj559940** [comment]
> > Added BitcoinAsia (BTCA) , World's first cryptocurrency based travel package company

**Comment by bitcoinasiasite** [comment]
Any update on merging change? @mj559940

**Review by mj559940 — APPROVED** [review]

**Comment by bitcoinasiasite** [comment]
@mj559940 When will it merge?

**Comment by bitcoinasiasite** [comment]
@mj559940 Any update on merge?

**Review by mj559940 — APPROVED** [review]

**Review by gamalielhere — APPROVED** [review]

**Pull request merged**
