### PR TITLE
Added Driveholic Token to Defaults

### PR DESCRIPTION
**Pull request by driveholic**

### CODE REVIEW

**Comment by driveholic** [comment]
Can you please change the from 		"name": "Driveholictoken",
to 		"name": "Driveholic Token",
?

not compulsory, but would be nice if you can.

**Comment by driveholic** [comment]
Hi, it's still not showing up on the default list ?

**Comment by gamalielhere** [comment]
@driveholic It will show on the default list when we make a release.

**Comment by driveholic** [comment]
@gamalielhere  that's superb! thank you !

**Pull request merged**
