### PR TITLE
MEW Phishing

### PR DESCRIPTION
**Pull request by checktheURL**

### CODE REVIEW

**Comment by 409H** [comment]
Hi @checktheURL - please can you reformat the JSON to be valid?

**Comment by checktheURL** [comment]
@409H Sorry I am not very technical. how can i do this?

**Comment by 409H** [comment]
Ah, no problem, I'll format it :smile:

**Comment by 409H** [comment]
https://urlscan.io/result/9cd9ec27-f1c0-4958-b836-fbe06b987796#summary

**Pull request merged**
