### PR TITLE
Add WALL token

### PR DESCRIPTION
**Pull request by ligi**

### CODE REVIEW

**Comment by 409H** [comment]
Hi Ligi, the address listed `0x0A057a87CE9C56D7e336B417c79cf30E8d27860B` doesn't have a contract deployed to issue tokens, can you describe that to me?

**Comment by ligi** [comment]
be sure to look on rinkeby - this is not on main-net: https://rinkeby.etherscan.io/address/0x0A057a87CE9C56D7e336B417c79cf30E8d27860B

**Comment by 409H** [comment]
Ah, my bad, excuse my mistake

**Comment by ligi** [comment]
No worries - thanks for the merge

**Pull request merged**
