### PR TITLE
Update and rename 0xbde8f7820b5544a49d34f9ddeacabedc7c0b5adc.json to …

### PR DESCRIPTION
**Pull request by Apollo18Crypto**
…0xBa7DCBa2Ade319Bc772DB4df75A76BA00dFb31b0

created new contract and had to air drop to previous contract token holders. please contact me if you need any further verification contact@apollo18.co.in

### CODE REVIEW

**Comment by gamalielhere** [comment]
@Apollo18Crypto Looks like you updated it properly.

**Comment by Apollo18Crypto** [comment]
I think the incorrect address was used because MEW is still showing coins from the old contract.
0xba7dcba2ade319bc772db4df75a76ba00dfb31b0 is the contract address of the new tokens

**Comment by gamalielhere** [comment]
The update will show once we make a new release.

**Comment by Apollo18Crypto** [comment]
Ohh okay. My apologies. Was the contract address correct then?

**Comment by gamalielhere** [comment]
Yes.

**Pull request merged**
