### PR TITLE
VersiCoin.json

### PR DESCRIPTION
**Pull request by dudegivemeaname**
Website will be www.versicoin.net, but not currently up.

### CODE REVIEW

**Comment by gamalielhere** [comment]
@dudegivemeaname please rename the token file to '<tokenaddress>.json`

**Comment by dudegivemeaname** [comment]
Alright, I got that changed for you.

Ren Peterson
Software Engineer / IT Solutions
(435)773-2353

**Comment by gamalielhere** [comment]
@dudegivemeaname the actual token file name. not the PR.

**Comment by dudegivemeaname** [comment]
Hah, oh goodness, changed that for you, my bad!

**Comment by gamalielhere** [comment]
@dudegivemeaname Actually forgot to add earlier, but the file name has to be the tokenaddress: `<tokenaddress>.json`

**Comment by dudegivemeaname** [comment]
Perfect, got that changed for you!

Ren Peterson
Software Engineer / IT Solutions
(435)773-2353

**Comment by dudegivemeaname** [comment]
Got that done for you! Thanks!

**Comment by dudegivemeaname** [comment]
When would the token be set as a default token?

Ren Peterson
Software Engineer / IT Solutions
(435)773-2353

**Pull request merged**
