### PR TITLE
Fail on blank fields

### PR DESCRIPTION
**Pull request by ligi**
+housekeeping for the scripts
+remove YUPIE token (decimals was "") - will contact the email mentioned in there so they can fix it if they want

### CODE REVIEW

**Comment by ligi** [comment]
just contacted the email in the list

**Comment by 409H** [comment]
@ligi did they get back to you?

**Comment by ligi** [comment]
unfortunately not :-/

**Comment by 409H** [comment]
Ok - will merge, and await a PR from them :smile:

**Pull request merged**
