### PR TITLE
Create 0x843C9AF34F698618F90C898E3967278a260c8d9A.json

### PR DESCRIPTION
**Pull request by cjrada**

### CODE REVIEW

**Review by alizere — APPROVED** [review]

**Comment by alizere** [comment]
>

**Comment by cjrada** [comment]
This PR is ready to be pulled in.  Logo information will come later.  Thanks.

**Review by gamalielhere — CHANGES_REQUESTED** [review]
Decimal is wrong based on information here:
https://www.ethvm.com/token/0x843C9AF34F698618F90C898E3967278a260c8d9A

**Comment by cjrada** [comment]
> Decimal is wrong based on information here:
> https://www.ethvm.com/token/0x843C9AF34F698618F90C898E3967278a260c8d9A

Correct, you are.  Much appreciated.  This has updated to 4.

**Review by gamalielhere — APPROVED** [review]

**Pull request merged**
