### PR TITLE
Added Tercet Network(TCNX) token to default

### PR DESCRIPTION
**Pull request by Dien0**

### CODE REVIEW

**Comment by Dien0** [comment]
its crashing on check token can you please advice on it.

**Comment by Dien0** [comment]
> is.

can you tell me if something is missing

**Comment by Dien0** [comment]
issue is still same, any fix on it ?

**Comment by gamalielhere** [comment]
@Dien0 your file is missing `.json` extension

**Comment by Dien0** [comment]
i had opened new pulled request its fixed, thanks agian :)

**Pull request closed without merging**
