### PR TITLE
Added EDC Token to Defaults

### PR DESCRIPTION
**Pull request by jimshanghai**
This EDC token is designed for people to record and reward their study history and education credits, will be loved by people. THANKS

### CODE REVIEW

**Comment by jimshanghai** [comment]
Thanks a lot for your reviewing.

**Comment by gamalielhere** [comment]
@jimshanghai would you be able to fix those conflicts? you seem to be overwritting alot of the recent changes. I can fix them for you if you want.

**Comment by gamalielhere** [comment]
@jimshanghai Merged your token here #577

**Comment by jimshanghai** [comment]
that would be fine if EDC can be merged into the list

**Comment by gamalielhere** [comment]
@jimshanghai It's already on the list. You can check it out on the mew site. 😄

**Comment by jimshanghai** [comment]
@gamalielhere please fix it for me, thanks

**Comment by jimshanghai** [comment]
I see, I may need to resubmit my token listing request. Thank you for your assistance anyway.

**Pull request closed without merging**
