### PR TITLE
Add TICO to default list

### PR DESCRIPTION
**Pull request by Topinvestmentcoin**

### CODE REVIEW

**Comment by gamalielhere** [comment]
Change filename to `.json`

**Comment by gamalielhere** [comment]
@Topinvestmentcoin whats the difference between this token and `0xa5db1d6f7a0d5bccc17d0bfd39d7af32d5e5edc6`?

**Comment by Topinvestmentcoin** [comment]
What I meant by merge was if the new file can replace the old files

**Comment by gamalielhere** [comment]
@Topinvestmentcoin is there any documentation on announcement for this?

**Comment by gamalielhere** [comment]
https://github.com/MyEtherWallet/ethereum-lists/commit/2f4d0d2e6975f7c0ea116e916b4dffb4b7e0b42e

**Pull request closed without merging**
