### PR TITLE
[Scam] Add EOSC impersonation scam

### PR DESCRIPTION
**Pull request by eosclassicteam**
Fake EOS Classic token airdrop on etherscan recently reported to our team

Official EOS Classic ( Coin )

+ Homepage: https://eos-classic.io

Fake EOS Classic ( ERC20 )

+ Homepage: https://eosclassic.co

### CODE REVIEW

**Comment by EOSclassic-EOSC** [comment]
There is nothing “fake” about the EOSclassic project and we believe that this pull request was made in bad faith in an attempt to damage our project. We have always been up front about the motivations behind our project: we believe that there was significant value created by the EOS community through the EOS token crowdsale and subsequent distribution, and felt that creating a token that would honor everyone’s original EOS token balances with re-enabled trading would create value in the broader EOS community.

Our code has been reviewed by the MyCrypto.com development team, and was deemed clean (see the EOS Classic discussion about half way down): https://www.coindesk.com/eos-blockchain-isnt-live-yet-getting-closer/

Relevant quote: “The creators use something of a complicated process for users to claim their tokens, but MyCrypto CEO Taylor Monahan asked her team to look at it, and they don't see anything dangerous about an EOS holder claiming EOS Classic tokens.”

Our smart contract code is open source, both verified on EtherScan (https://etherscan.io/address/0xce3ad07c9c7a5f89d39eb1449913d3feecabcf8d#code)  and posted in Truffle-ready format on GitHub: https://github.com/EOSclassic-EOSC/EOSclassic

Further, we have received now over 3,100 organic token claims through our marketing and outreach efforts, with significant momentum in particular from the Korean EOS community.  

To our claim that this pull request was done in bad faith, we provide a snapshot where the first mention of our domain was made in the EOS Classic Telegram: https://i.imgur.com/zPcC2Ym.png 

There have been several additional mentions of our ERC20 token project in their channel since our domain was shared in their Telegram channel on June 6th, 2018. It’s unfortunate that we share the same name, but when we launched there was no competition to speak of, so we ran with the EOSclassic name.

There is no reason why these two projects cannot co-exist, as our project, EOSclassic intends to stay as a token on the Ethereum blockchain, while EOS-Classic.io has forked Ethereum to create their own mineable blockchain.

@gamalielhere we ask that this pull request be reverted as soon as you or another maintainer can review our case, as anyone with Metamask installed cannot access our site. Thank you for your time.

**Comment by gamalielhere** [comment]
@EOSclassic-EOSC [Reverted change](https://github.com/kvhnuke/etherwallet/commit/dc9eb0d85a1f5de046bbd58a1beba086c018cc2e) until the issue is resolved among both eosc teams

**Comment by EOSclassic-EOSC** [comment]
Thank you, @gamalielhere!

**Comment by 409H** [comment]
@gamalielhere can you also revert the change in the url darklist so the CI won't fail on `MetaMask/eth-phishing-detect` when I revert? Thanks

**Comment by EOSclassic-EOSC** [comment]
@gamalielhere yes please follow up with @409H's request, our site is still inaccessible to anyone with Metamask installed.

**Comment by eosclassicteam** [comment]
@gamalielhere @EOSclassic-EOSC Hello, thanks for merging this PR :heart: 

eos-classic.io was the first project to use the symbol "EOS Classic" and the ticker "EOSC". In the case of "Bitcoin Classic" or "Bitcoin Clashic (Yes this is the fork of Bitcoin Cash) ", avoiding the use of same ticker or same coin name is a strict rule, in order to prevent name conflict on the services like CoinMarketCap or Coin exchanges. Also there is the case that exchanges and services changed the ticker of bitcoin cash from "BCC" to "BCH" in order to avoid conflict on trading coins. 

**Therefore using the same coin name on the different coin architecture or project must be avoided in a same manner.**

If @EOSclassic-EOSC you guys or team are planning to create a valid project for creating the token, please change your coin name or token to different symbol that avoids conflict with our team.

If the changes are not done by a reasonable time our team will report eosclassic.co or the following token https://etherscan.io/address/0xce3ad07c9c7a5f89d39eb1449913d3feecabcf8d as a illegal impersonation of EOS Classic [EOSC] coin which will be available on the next release of MyEtherWallet or MyCrypto.

We will keep monitor the situation and pr requests.

**Pull request merged**
