### PR TITLE
Added NCC Token to Defaults

### PR DESCRIPTION
**Pull request by needscoinadmin**
Dear MyEtherWallet Support Team, thanks for giving your valuable time to check out our NeedsCoin Token. We are a decentralized team of freelance php programmer, front-end and back-end developer and also social media market going to provide and develop blockchain based solution for e-commerce, outsourcing application, crypto trading application using Ethereum ERC20 Token. Please help us to list our NeedsCoin Token to your default token list. It'll become our another milestone. We'll be glad to assist your providing more info if you need. Please feel free to email us at: admin@needscoin.info or help@needscoin.info. Thanks, NeedsCoin Developer Team

### CODE REVIEW

**Comment by gamalielhere** [comment]
@needscoinadmin you need to fix the formatting issues, don't remove the empty properties.

**Comment by gamalielhere** [comment]
@needscoinadmin it's up to you, you can just update this branch if needed. There's a template of the token object on the README

**Comment by needscoinadmin** [comment]
@gamalielhere, thanks. trying again.

**Comment by needscoinadmin** [comment]
Hi @gamalielhere, if we want to change our Symbol from NCC to NCX then what we should do. Do we need to Revert the mast marge you made or simply you can do it here. thanks.

Why we need to change because we observed that NeuroChain have same symbol NCC, so we want to change our NCC to NCX and we've also checked that there is no Token with NCX, so it'll be a good step for us to be unique. Thanks.

**Comment by gamalielhere** [comment]
@needscoinadmin you just have to update the token file, and I'll compile it;

**Pull request merged**
