### PR TITLE
Added WCN Token to Defaults

### PR DESCRIPTION
**Pull request by WorldCoinNetwork**

### CODE REVIEW

**Comment by gamalielhere** [comment]
Hey @WorldCoinNetwork, do you have any documentation on the change of address, token name, etc?

**Comment by WorldCoinNetwork** [comment]
yes! what do you need

**Comment by gamalielhere** [comment]
Any type of published document, it may be a website announcement (preferred) or an article. @WorldCoinNetwork

**Comment by WorldCoinNetwork** [comment]
https://icolink.com/finance-ico-list/ad/world-coin-network,576.html
https://concourseq.io/Q/World_Coin_Network
https://lastcrypto.com/icos/worldcoinnetwork.php
https://www.coinmarketplus.com/token/world-coin-network/
https://foundico.com/ico/world-coin-network.html
https://sangus.org/ico/1198
http://www.bitcoinx.com/ico/world-coin-network/
https://www.coinhills.com/ico/view/world-coin-network/
https://icoexpert.biz/icos/world-coin-network/
https://cryptocoin.news/ico/world-coin-network-wcn-ico/
https://icobuffer.com/projects/world-coin-network/
https://en.insider.pro/calendars/ICO/world-coin-network/

**Pull request merged**
