### PR TITLE
Update and rename TKLN to TAN

### PR DESCRIPTION
**Pull request by VitaliyTAN**

### CODE REVIEW

**Comment by gamalielhere** [comment]
Is there any documentation for this change?

**Comment by VitaliyTAN** [comment]
Yes, here is a post in the official telegram chat:

**Comment by VitaliyTAN** [comment]
Here is an ad with token data:

**Comment by VitaliyTAN** [comment]
@gamalielhere Anything else you need to confirm?

**Comment by gamalielhere** [comment]
@VitaliyTAN nope. Thanks for cooperating!

**Pull request merged**
