### PR TITLE
Added Sharder (SS) Token to Defaults

### PR DESCRIPTION
**Pull request by ben-xy**
Update the upgraded contract address and ref links.

### CODE REVIEW

**Comment by xxxxyy1** [comment]
Hello Ben,
How can I make my token ICO promotion display on Etherscan.io ads platform?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by gamalielhere** [comment]
@ben-xy Hey Ben, do you have a published documentation for the change of address?

**Comment by ben-xy** [comment]
@gamalielhere  Hi gamalielhere, the published notice is here: https://oss.sharder.org/sharder/notice/Sharder(SS)-Migration-Notice.txt

**Comment by gamalielhere** [comment]
@ben-xy thanks!

**Pull request merged**
